// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwhH2YU9GlZUf5yAUweJwyLnCmPzNpwk',
    appId: '1:248263650750:web:3bcc6a1cb0ba1a65c29def',
    messagingSenderId: '248263650750',
    projectId: 'parking-app-b18a3',
    authDomain: 'parking-app-b18a3.firebaseapp.com',
    storageBucket: 'parking-app-b18a3.appspot.com',
    measurementId: 'G-WJYJZL9L14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuadxzopyBBLE4VJ6ZhNpXgCKgFgXKWQ',
    appId: '1:248263650750:android:d4a58ef83bd6b527c29def',
    messagingSenderId: '248263650750',
    projectId: 'parking-app-b18a3',
    storageBucket: 'parking-app-b18a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCj8r4M7UzTgyxKHGxN2lnzMdvkHekro',
    appId: '1:248263650750:ios:62d2c14eb604d6dec29def',
    messagingSenderId: '248263650750',
    projectId: 'parking-app-b18a3',
    storageBucket: 'parking-app-b18a3.appspot.com',
    iosClientId: '248263650750-43flhb1ql59kbebigfqf91n5b5f7383u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCj8r4M7UzTgyxKHGxN2lnzMdvkHekro',
    appId: '1:248263650750:ios:62d2c14eb604d6dec29def',
    messagingSenderId: '248263650750',
    projectId: 'parking-app-b18a3',
    storageBucket: 'parking-app-b18a3.appspot.com',
    iosClientId: '248263650750-43flhb1ql59kbebigfqf91n5b5f7383u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
